macro(astl_setup_gtest)
    option(ASTL_GTESTS "Enables or disables build of gtests" OFF)
    option(ASTL_CTEST  "Enable CTest for continuous testing" OFF)
    if (ASTL_GTESTS)
        find_package(GTest REQUIRED)
        if (ASTL_CTEST)
            include(CTest)
        endif()
        enable_testing()
    endif()
endmacro()
