macro(astl_setup_gtest)
    option(ASTL_GTESTS "Enables or disables build of gtests" OFF)
    if (ASTL_GTESTS)
        find_package(GTest REQUIRED)
        include(CTest)
        enable_testing()
        add_subdirectory(${CMAKE_SOURCE_DIR}/gtests)
    endif()
endmacro()
