name: CI 

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare-dependencies
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo mkdir build && cd build && sudo cmake .. && sudo make install
    - name: configure
      run: mkdir build && cd build && cmake -DASTL_GTESTS=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
